### ISSUE TITLE
[Bug]: About code execution in group chat

### ISSUE THREAD

**Issue by szwang-seedtech** [ag2ai/ag2#16]
### Describe the bug

Does anyone have this issue: when one agent proposed a script to be executed during group chat, all the rest of agents will try to execute the code, even though the execution is already done. I am using 0.3.1
![Screenshot 2024-11-14 103649](https://github.com/user-attachments/assets/54c06a1f-0351-4118-93cd-437045f8a289)

**Comment by marklysze** [comment]
I haven't seen that myself, can you provide a code sample to replicate?

**Comment by szwang-seedtech** [comment]
@marklysze this is the code i am using and agent_llm_config is just some commen setups, keys, models...i tried both 4o and 4o-mini
`import autogen
from autogen import ConversableAgent

Solver_prompt = """
This is a collaborative task-solving team. 

Here is a new task: {input}
"""

task = "write me a bubble sort sample code, test and save as file"

def solver_prompt_message(sender, recipient, context):
    print(context)
    return Solver_prompt.format(input=context["question"])

agent_list = [
    ConversableAgent(
        name="Seed_Assistant",
        system_message="You are Meta-Expert, an extremely clever expert with the unique ability to collaborate with multiple experts to tackle any task and solve any complex problems, please reply with 'TERMINATE'.",
        description="Meta-Expert is a highly skilled agent capable of working with multiple experts to solve complex problems.",
        llm_config=agent_llm_config,
        human_input_mode="NEVER",
        code_execution_config={"use_docker": False},
    ),
    ConversableAgent(
        name="coder",
        system_message="write code, reply 'TERMINATE' to conclude.",
        description="write code",
        llm_config=agent_llm_config,
        human_input_mode="NEVER",
        code_execution_config={"use_docker": False},
    ),
    ConversableAgent(
        name="reviewer",
        system_message="review code, reply 'TERMINATE' to conclude.",
        description="review code",
        llm_config=agent_llm_config,
        human_input_mode="NEVER",
        code_execution_config={"use_docker": False},
    ),
]

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    code_execution_config=False,
)

groupchat = autogen.GroupChat(
        agents=agent_list,
        messages=[],
        send_introductions=True,
        speaker_selection_method="auto",
        allow_repeat_speaker=False,
    )

manager = autogen.GroupChatManager(
        groupchat=groupchat, llm_config=agent_llm_config
    )

user_proxy.initiate_chats(
    [
        {
            "recipient": manager,
            "message": solver_prompt_message,
            "summary_method": "last_msg",
            "question": task,
        },
    ]
)`

**Comment by szwang-seedtech** [comment]
@marklysze and this is the log i get. Except the agent propose the code, all the other agents will try to execute the code, even though the execution is already succeeded.
********************************************************************************
Starting a new chat....

********************************************************************************
{'question': 'write me a bubble sort sample code, test and save as file', 'sender': <autogen.agentchat.user_proxy_agent.UserProxyAgent object at 0x000001E63025EC00>, 'carryover': []}
user_proxy (to chat_manager):


This is a collaborative task-solving team. 

Here is a new task: write me a bubble sort sample code, test and save as file


--------------------------------------------------------------------------------

Next speaker: coder

coder (to chat_manager):

Sure! Below is a sample code for the bubble sort algorithm, along with a simple test case. I will also provide code to save it as a file.

```python
# bubble_sort.py

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        # Track if a swap was made
        swapped = False
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]  # Swap
                swapped = True
        # If no two elements were swapped, the array is sorted
        if not swapped:
            break
    return arr

# Test the bubble sort function
if __name__ == "__main__":
    test_array = [64, 34, 25, 12, 22, 11, 90]
    print("Unsorted array:", test_array)
    sorted_array = bubble_sort(test_array)
    print("Sorted array:", sorted_array)
```

Now, let's save this code to a file named `bubble_sort.py`.

```python
# Save the bubble sort code to a file
code = """def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        swapped = False
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                swapped = True
        if not swapped:
            break
    return arr

if __name__ == "__main__":
    test_array = [64, 34, 25, 12, 22, 11, 90]
    print("Unsorted array:", test_array)
    sorted_array = bubble_sort(test_array)
    print("Sorted array:", sorted_array)
"""

# Write to file
with open("bubble_sort.py", "w") as file:
    file.write(code)

print("Bubble sort code has been saved to bubble_sort.py")
```

This code defines the bubble sort function, tests it with a sample array, and saves the entire code to a file named `bubble_sort.py`.

Let me know if you need any further assistance!

TERMINATE

--------------------------------------------------------------------------------

Next speaker: reviewer


>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...

>>>>>>>> EXECUTING CODE BLOCK 1 (inferred language is python)...
reviewer (to chat_manager):

exitcode: 0 (execution succeeded)
Code output:
Unsorted array: [64, 34, 25, 12, 22, 11, 90]
Sorted array: [11, 12, 22, 25, 34, 64, 90]

Bubble sort code has been saved to bubble_sort.py


--------------------------------------------------------------------------------

Next speaker: Seed_Assistant


>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...

>>>>>>>> EXECUTING CODE BLOCK 1 (inferred language is python)...
Seed_Assistant (to chat_manager):

exitcode: 0 (execution succeeded)
Code output:
Unsorted array: [64, 34, 25, 12, 22, 11, 90]
Sorted array: [11, 12, 22, 25, 34, 64, 90]

Bubble sort code has been saved to bubble_sort.py


--------------------------------------------------------------------------------

Next speaker: reviewer

reviewer (to chat_manager):

TERMINATE

**Comment by marklysze** [comment]
Hey @szwang-seedtech, I'll reply with a few messages. My recommendations are in the last message...

When I ran your code with Llama3.1 using Ollama, it actually worked:

```
********************************************************************************
Starting a new chat....

********************************************************************************
{'question': 'write me a bubble sort sample code, test and save as file', 'sender': <autogen.agentchat.user_proxy_agent.UserProxyAgent object at 0x7fce5b338a50>, 'carryover': []}
user_proxy (to chat_manager):


This is a collaborative task-solving team. 

Here is a new task: write me a bubble sort sample code, test and save as file


--------------------------------------------------------------------------------

Next speaker: coder

coder (to chat_manager):

Here's a Python implementation of the Bubble Sort algorithm:

```python
def bubble_sort(arr):
    """
    Sorts an array in ascending order using the Bubble Sort algorithm.

    Args:
        arr (list): The list to be sorted.

    Returns:
        list: The sorted list.
    """

    n = len(arr)

    for i in range(n-1):
        # Create a flag that will allow the function to terminate early if there's nothing left to sort
        swapped = False

        # Start looking at each item of the list one by one, comparing it with its adjacent value
        for j in range(0, n-i-1):

            # If we find an element that is greater than its adjacent element then swap them
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                swapped = True

        # If no two elements were swapped by inner loop, the list is sorted and we can terminate
        if not swapped:
            break

    return arr


# Test the function
arr = [64, 34, 25, 12, 22, 11, 90]
print("Original array:", arr)
sorted_arr = bubble_sort(arr)
print("Sorted array:", sorted_arr)


# Save as file (you can use a code editor to create a new file or append this code to an existing one)

TERMINATE

--------------------------------------------------------------------------------

Next speaker: Seed_Assistant


>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...
Seed_Assistant (to chat_manager):

exitcode: 0 (execution succeeded)
Code output: 
Original array: [64, 34, 25, 12, 22, 11, 90]
Sorted array: [11, 12, 22, 25, 34, 64, 90]


--------------------------------------------------------------------------------

Next speaker: coder

coder (to chat_manager):

TERMINATE

--------------------------------------------------------------------------------
```

**Comment by marklysze** [comment]
When I tried your code with gpt-4o, yes it did what you experienced by running code with each agent.

I believe the reason this is happening is:
All agents had a `code_execution_config` that wasn't `False`. When agents have a code execution config, they will look for code in previous messages and try and execute it. This happens before it goes to an LLM to generate a reply. So if an agent who can execute code sees code in previous messages it will execute the code and then the flow moves on to the next agent, it won't go to the LLM.

The best thing to do is to set `code_execution_config=False` if you do not want the agent to execute code (or leave it out as it defaults to `False`.

A couple of additional suggestions:
- If you are running a group chat, the group chat manager works out who speaks next so you may not need the `Seed_Assistant` in this case.
- If you want an agent to both execute code and then in their next turn not execute code you can use the `last_n_messages` setting for your code_execution_config - this means the agent will only look back two messages to see if there are any code suggestions and will execute if it finds it but not if it doesn't and then can move on to reviewing rather than executing. See the example below.

Can you try my updated code, can you try this:

```
Solver_prompt = """
This is a collaborative task-solving team. 

Here is a new task: {input}
"""

task = "write me a bubble sort sample code, test and save as file"

def solver_prompt_message(sender, recipient, context):
    print(context)
    return Solver_prompt.format(input=context["question"])

agent_list = [
    ConversableAgent(
        name="coder",
        system_message="write code, reply 'TERMINATE' to conclude.",
        description="writes code",
        llm_config=agent_llm_config,
        human_input_mode="NEVER",
        code_execution_config=False
    ),
    ConversableAgent(
        name="reviewer",
        system_message="review code, reply 'TERMINATE' to conclude.",
        description="reviews code",
        llm_config=agent_llm_config,
        human_input_mode="NEVER",
        code_execution_config={"use_docker": False, "last_n_messages": 2}, # Reviewer can execute code and will review (not execute) if there's no code in the last two messages
    ),
]

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    code_execution_config=False,
)

groupchat = autogen.GroupChat(
        agents=agent_list,
        messages=[],
        send_introductions=True,
        speaker_selection_method="auto",
        allow_repeat_speaker=False,
    )

manager = autogen.GroupChatManager(
        groupchat=groupchat, llm_config=agent_llm_config
    )

user_proxy.initiate_chats(
    [
        {
            "recipient": manager,
            "message": solver_prompt_message,
            "summary_method": "last_msg",
            "question": task,
        },
    ]
)
```

**Comment by szwang-seedtech** [comment]
@marklysze Thank you for your help! I tried a few other things such as adding "Do not execute the same script again if it has already been executed", but seems not working.
But your code may hit onto something. When I set "last_n_messages": 1 in every code executior, no repetitive code execution occurs any more!
So this may be related to how 4o and 4o-mini recognizes code execution?

**Comment by marklysze** [comment]
Ah okay, good to hear that you have no more code execution - though I think the code_execution_config is the main thing to set to false if you want to minimise it.

The code execution parameter, last_n_messages, is used internally to limit the number of messages checked for any code - and if it finds the code it will execute it (before it goes to the LLM, like 4o or 4o-mini). So that's why it's important to limit it and also to take code_execution_config off agents that you don't want to execute code.

Thanks @szwang-seedtech :)
