### ISSUE TITLE
[Bug]: import autogen

### ISSUE THREAD

**Issue by MarkLo127** [ag2ai/ag2#167]
I want import autogen

import autogen

but error message say:

ModuleNotFoundError: No module named 'openai.lib._parsing'

**Comment by qingyun-wu** [comment]
@MarkLo127, could you make sure you have the latest openai version and latest autogen? 

```
pip uninstall openai pyautogen ag2
```
and then do
```
pip install pyautogen
```

**Comment by MarkLo127** [comment]
The problem Wii be solved

tks

**Comment by qingyun-wu** [comment]
@MarkLo127 problem is solved? If so, could you close the PR? Thanks!

**Comment by bassilkhilo** [comment]
Hi @MarkLo127 

Please take a look at https://github.com/ag2ai/ag2/issues/169

This may solve the issue.

**Comment by Hk669** [comment]
closing this issue, as @MarkLo127 mentioned the problem is solved. Thanks @qingyun-wu !
