### ISSUE TITLE
[Feature Request]: Migrate documentation from Docusaurus to Mintlify

### ISSUE THREAD

**Issue by harishmohanraj** [ag2ai/ag2#209]
### Is your feature request related to a problem? Please describe.

The current documentation can be improved to provide a more modern look and enhanced user experience, ensuring a visually appealing and feature-rich documentation experience for users.

### Describe the solution you'd like

Migrate the existing documentation to Mintlify to provide:

- A modern, visually appealing, and feature-rich documentation experience for users.
- AI-powered search capability for enhanced interactivity.

### Additional context

Subtasks:

- [x]  Configure Mintlify for the project
- [x]  Set up CI/CD for automated deployments
- [x]  Integrate all documentation pages
    - [x]  Ensure existing MDX files are compatible with Mintlify
    - [x]  Add Landing page, Blog pages, and Examples pages
    - [x]  Ensure API Reference docs generated by `pydoc-markdown` are compatible
    - [x]  Ensure MDX files generated by the `process_notebooks` script are compatible

**Comment by JASchilz** [comment]
@davorrunje I'm not sure if I'm going crazy, but this seems to have broken ag2's documentation links.

This is what I see when I visit any of the site's documentation links:

![image](https://github.com/user-attachments/assets/1bddf0c9-8a26-4c27-941b-18095bd07ad1)
