### ISSUE TITLE
[Bug]: https://ag2ai.github.io/ag2/docs/notebooks/agentchat_graph_rag_neo4j/  Notebook: cannot use pre-made database, I have to create a new one every time I run the notebook.

### ISSUE THREAD

**Issue by Tylersuard** [ag2ai/ag2#234]
### Describe the bug

When using this notebook, I cannot bring my own database, I have to build a new database every time I run the notebook.  If I bring my own database, I get attribute errors.

### Steps to reproduce

Run the notebook, but comment out this line:
query_engine.init_db(input_doc=input_documents)

That line deletes all records in whatever database you designate and creates a new database.

### Expected Behavior

I would like to be able to use this notebook to connect to a pre-existing neo4j database, rather than having to create a new one from scratch every time we run the notebook.

**Comment by Eric-Shang** [comment]
You were right. It's solved yesterday. Please check the updated notebook. You could use the connect_db method.

**Comment by Tylersuard** [comment]
@Eric-Shang Thank you! I appreciate the quick response.  I am still getting errors though, I think because I am using Azure OpenAI.  Why did you decide that agents with graph capabilities cannot use an llm config? How should I set these agents up for Azure OpenAI without one?

**Comment by tyler-suard-parker** [comment]
![image](https://github.com/user-attachments/assets/7a23e691-8813-47ed-8b22-e878c479a75c)
Additionally, the docstring for the add_to_agent() method says it can only be added to a user proxy agent, but in the notebook we are adding it to a conversable agent.

I tried following the instructions here for setting LlamaIndex to use Azure Openai (https://docs.llamaindex.ai/en/stable/examples/customization/llms/AzureOpenAI/) , but when I run your code it is still trying to ping openai.com instead of azure.

**Comment by Eric-Shang** [comment]
Are you saying you are following this customization?
`api_key = ""
azure_endpoint = "https://.openai.azure.com/"
api_version = "2023-07-01-preview"

llm = AzureOpenAI(
    model="gpt-35-turbo-16k",
    deployment_name="my-custom-llm",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

# You need to deploy your own embedding model as well as your own chat completion model
embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name="my-custom-embedding",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)`

If you pass in these 2 parameters to the neo4j query engine, it should connect to Azure. We didn't hardcode it.

**Comment by tyler-suard-parker** [comment]
@Eric-Shang thank you, I understand more about the issue now.  However, when I follow your instructions and create the llm and embed_model objects, and then pass both of them into the Neo4jGraphQueryEngine, the agents are still not trying to connect to Azure, they are trying to connect to openai.com.  Please see my code below and the output.

llm = AzureOpenAI(
model="gpt-4",
deployment_name="gpt-4", #I also tried this with engine=, it did not work
api_key=os.environ.get("OPENAI_API_KEY_1"),
azure_endpoint=os.environ.get("OPENAI_ENDPOINT_1"),
api_version="2024-02-01",
)

embed_model = AzureOpenAIEmbedding(
model="text-embedding-3-small",
deployment_name="text-embedding-3-small",
api_key=os.environ.get("OPENAI_EMBEDDINGS_KEY"),
azure_endpoint=os.environ.get("OPENAI_EMBEDDINGS_ENDPOINT"),
api_version="2024-02-01",
)

query_engine = Neo4jGraphQueryEngine(
    username="neo4j",  # Change these as needed
    password="password",
    host="host_url",
    port=1111,
    database="neo4j",
    llm=llm,
    embedding=embed_model,
)
query_engine.connect_db()


from autogen.agentchat.contrib.graph_rag.neo4j_graph_rag_capability import Neo4jGraphCapability
from autogen_llm_config import llm_config_no_functions

# Create a ConversableAgent (no LLM configuration)
graph_rag_agent = ConversableAgent(
    name="rag_agent",
    human_input_mode="NEVER",
)

# Associate the capability with the agent
graph_rag_capability = Neo4jGraphCapability(query_engine)
graph_rag_capability.add_to_agent(graph_rag_agent)

# Create a user proxy agent to converse with our RAG agent
user_proxy = UserProxyAgent(name="user_proxy", human_input_mode="ALWAYS", code_execution_config=False, llm_config=llm_config_no_functions)

user_proxy.initiate_chat(graph_rag_agent, message="How are orders for customer 904504 compared to this time last year?")

OUTPUT:
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.0 302 Moved Temporarily"
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.0 302 Moved Temporarily"

**Comment by tyler-suard-parker** [comment]
I will close this issue and create a new one
