### ISSUE TITLE
[Issue]: Outdated https://docs.ag2.ai/docs/contributor-guide/documentation

### ISSUE THREAD

**Issue by AgentGenie** [ag2ai/ag2#271]
### Describe the issue

We migrated doc website to mintlify. Need to update contributor-guide/documentation page with https://github.com/ag2ai/ag2/blob/17ab5d69e0bb4ccdd4e021fda5e2fca0fec5314b/website/README.md

**Comment by qingyun-wu** [comment]
@harishmohanraj Could you update it? thank you!
