### ISSUE TITLE
[Bug]: agentchat_graph_rag_neo4j/ Notebook: program keeps trying to connect to api.openai.com, even though I have set my endpoint to azure

### ISSUE THREAD

**Issue by tyler-suard-parker** [ag2ai/ag2#288]
### Describe the bug

I am following the notebook here:

https://docs.ag2.ai/notebooks/agentchat_graph_rag_neo4j#using-neo4js-graph-database-with-ag2-agents-for-question-and-answering

I modified the example code to use Azure OpenAI instead of Openai, but the code is still trying to connect to OpenAI.

### Steps to reproduce

Run everything in the notebook before the cell that says "instead of creating a new property graph..."

Then use the following, with your own Azure OpenAI credentials:

llm = AzureOpenAI(
model="gpt-4",
deployment_name="gpt-4", #I also tried this with engine=, it did not work
api_key=os.environ.get("OPENAI_API_KEY_1"),
azure_endpoint=os.environ.get("OPENAI_ENDPOINT_1"),
api_base = azure_endpoint,
api_version="2024-02-01",
)

embed_model = AzureOpenAIEmbedding(
model="text-embedding-3-small",
deployment_name="text-embedding-3-small",
api_key=os.environ.get("OPENAI_EMBEDDINGS_KEY"),
azure_endpoint=os.environ.get("OPENAI_EMBEDDINGS_ENDPOINT"),
api_version="2024-02-01",
)

query_engine = Neo4jGraphQueryEngine(
username="neo4j", 
password="password",
host="host_url",
port=1111,
database="neo4j",
llm=llm,
embedding=embed_model,
)
query_engine.connect_db()

from autogen.agentchat.contrib.graph_rag.neo4j_graph_rag_capability import Neo4jGraphCapability
from autogen_llm_config import llm_config_no_functions  #this is my own config that points to Azure OpenAI

graph_rag_agent = ConversableAgent(
name="rag_agent",
human_input_mode="NEVER",
)

graph_rag_capability = Neo4jGraphCapability(query_engine)
graph_rag_capability.add_to_agent(graph_rag_agent)

user_proxy = UserProxyAgent(name="user_proxy", human_input_mode="ALWAYS", code_execution_config=False, llm_config=llm_config_no_functions)

user_proxy.initiate_chat(graph_rag_agent, message="How are orders for customer 904504 compared to this time last year?")

OUTPUT:
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.0 302 Moved Temporarily"
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.0 302 Moved Temporarily"

Even though I have set my LLM to call azure, it still won't do that.  It still keeps calling api.openai.com/v1/chat/completions.

### Model Used

gpt-4o

### Expected Behavior

The module should have called Azure OpenAI

### Additional Information

v0.6.0

**Comment by tyler-suard-parker** [comment]
@Eric-Shang @sonichi @qingyun-wu

**Comment by Eric-Shang** [comment]
Hi @tyler-suard-parker. Sorry for late reply. I just got back from my trip yesterday. And I didn't use Azure before and it took me some time to set it up.

It seems the notebook instructions are working for me, although my 1k/m rate limit is too low  (I'm using the free version):

```
Retrying llama_index.llms.openai.base.OpenAI._chat in 0.686371750517236 seconds as it raised RateLimitError: Error code: 429 - {'error': {'code': '429', 'message': 'Requests to the ChatCompletions_Create Operation under Azure OpenAI API version 2024-08-01-preview have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 8 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.'}}.
```

And I verified it didn't hit my openai endpoint. 

Here are my guesses:

1. Are you using the correct Azure api keys and models (which needs to be deployed first)? 
2. Are you sure the llm_config_no_functions is set properly? Could you give a shot by setting it to false?

**Comment by marklysze** [comment]
Hey @tyler-suard-parker,  I've been able to test successfully with this code block in place in the notebook where noted.

Two Azure model deployments (names as noted):
"gpt-4o-mini"
"text-embedding-3-small"

```
from llama_index.llms.azure_openai import AzureOpenAI
from llama_index.embeddings.azure_openai import AzureOpenAIEmbedding

llm = AzureOpenAI(
model="gpt-4o-mini",
deployment_name="gpt-4o-mini",
api_key=azure_api_key,
azure_endpoint=azure_endpoint,
api_base = azure_endpoint,
api_version="2024-08-01-preview",
)

embed_model = AzureOpenAIEmbedding(
model="text-embedding-3-small",
deployment_name="text-embedding-3-small",
api_key=azure_api_key,
azure_endpoint=azure_endpoint,
api_version="2023-05-15",
)

query_engine = Neo4jGraphQueryEngine(
username="neo4j",
password="<mypassword>",
host="bolt://<myneo4jip>",
port=7687,
database="neo4j",
llm=llm,
embedding=embed_model,
)
query_engine.connect_db()

from autogen.agentchat.contrib.graph_rag.neo4j_graph_rag_capability import Neo4jGraphCapability
# from autogen_llm_config import llm_config_no_functions #this is my own config that points to Azure OpenAI

llm_config_no_functions = {
    "config_list":
    [
        {
            "api_type": "azure",
            "api_version": "2024-08-01-preview",
            "model": "gpt-4o-mini",
            "base_url": azure_endpoint,
            "api_key": azure_api_key,
            "cache_seed": None
        }
    ]
}


graph_rag_agent = ConversableAgent(
name="rag_agent",
human_input_mode="NEVER",
)

graph_rag_capability = Neo4jGraphCapability(query_engine)
graph_rag_capability.add_to_agent(graph_rag_agent)

user_proxy = UserProxyAgent(name="user_proxy", human_input_mode="ALWAYS", code_execution_config=False, llm_config=llm_config_no_functions)

user_proxy.initiate_chat(graph_rag_agent, message="Which company is the employer?")
```

In relation to what @Eric-Shang asked, if you're able to share your `llm_config_no_functions` that may help diagnose it.

**Comment by tyler-suard-parker** [comment]
> Hi @tyler-suard-parker. Sorry for late reply. I just got back from my trip yesterday. And I didn't use Azure before and it took me some time to set it up.
> 
> It seems the notebook instructions are working for me, although my 1k/m rate limit is too low (I'm using the free version):
> 
> ```
> Retrying llama_index.llms.openai.base.OpenAI._chat in 0.686371750517236 seconds as it raised RateLimitError: Error code: 429 - {'error': {'code': '429', 'message': 'Requests to the ChatCompletions_Create Operation under Azure OpenAI API version 2024-08-01-preview have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 8 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.'}}.
> ```
> 
> And I verified it didn't hit my openai endpoint.
> 
> Here are my guesses:
> 
> 1. Are you using the correct Azure api keys and models (which needs to be deployed first)?
> 2. Are you sure the llm_config_no_functions is set properly? Could you give a shot by setting it to false?

@Eric-Shang Thank you so much for your hard work on this.  I appreciate you setting up Azure to try it out.

I tried setting my llm_config_no_functions to false, and it had no effect.  That same config works with Autogen in other scripts.

I tested my llm = AzureOpenAI() code by running llm.chat with some example messages, and that worked fine.  Then I tested my embed_model = AzureOpenAIEmbedding() code, and that worked fine too.

However, when I try to run the .initiate_chat line in your notebook, I am still getting:

[venv/Lib/site-packages/llama_index/llms/openai/utils.py:507)     raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)

ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

Even though I have set my api keys for azure it looks like Llamaindex is still looking for the API key for openai.com?

**Comment by tyler-suard-parker** [comment]
@marklysze Thank you for your help.  I ran the exact code you showed, just inputting my credentials, and I am still getting this error:

``` 
[44](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:44)         raise ImportError(
     [45](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:45)             "`llama-index-llms-openai` package not found, "
     [46](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:46)             "please run `pip install llama-index-llms-openai`"
     [47](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:47)         )
     [48](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:48)     except ValueError as e:
---> [49](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:49)         raise ValueError(
     [50](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:50)             "\n******\n"
     [51](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:51)             "Could not load OpenAI model. "
     [52](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:52)             "If you intended to use OpenAI, please check your OPENAI_API_KEY.\n"
     [53](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:53)             "Original error:\n"
     [54](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:54)             f"{e!s}"
     [55](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:55)             "\nTo disable the LLM entirely, set llm=None."
     [56](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:56)             "\n******"
     [57](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:57)         )
     [59](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:59) if isinstance(llm, str):
     [60](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:60)     splits = llm.split(":", 1)

ValueError: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******
``` 

As I mentioned to Eric, I have tried bot the llm and the embedding model separately and they both work using those same credentials.

**Comment by tyler-suard-parker** [comment]
@marklysze   Here is the code you sent me with some tests in between:

``` 
from llama_index.llms.azure_openai import AzureOpenAI
from llama_index.embeddings.azure_openai import AzureOpenAIEmbedding

api_key=""
azure_endpoint=""
api_version="2024-06-01"
temperature=0.0

llm = AzureOpenAI(
model="",
deployment_name="",
api_key="",
azure_endpoint="https://.openai.azure.com/",
api_base = "https://.openai.azure.com/",
api_version="2024-08-01-preview",
)

from llama_index.core.llms import ChatMessage
messages = [
    ChatMessage(role="system", content="You are a pirate with colorful personality."),
    ChatMessage(role="user", content="Hello"),
]

response = llm.chat(messages)
print(response)
``` 
Output: Ahoy there, matey! How be the winds fairin' for ye today? What adventure or treasure be ye seekin' on the vast seas of conversation?

```
embed_model = AzureOpenAIEmbedding(
model="text-embedding-3-small",
deployment_name="text-embedding-3-small",
api_key=api_key,
azure_endpoint=azure_endpoint,
api_version="2024-02-01",
)

embedding = embed_model.get_text_embedding("Sample text for embedding")
print(embedding)
``` 
Output: [0.021276075392961502, 0.009070326574146748, 0.02229788526892662, ... ]


``` 
query_engine = Neo4jGraphQueryEngine(
username="neo4j",
password="parker1234",
host="neo4j://cor089ya166",
port=7687,
database="neo4j",
llm=llm,
embedding=embed_model,
)
query_engine.connect_db()

from autogen.agentchat.contrib.graph_rag.neo4j_graph_rag_capability import Neo4jGraphCapability

llm_config_no_functions = {
    "config_list":
    [
        {
            "api_type": "azure",
            "api_version": "2024-06-01",
            "model": "gpt-4",
            "base_url": azure_endpoint,
            "api_key": api_key,
            "cache_seed": None
        }
    ]
}


graph_rag_agent = ConversableAgent(
name="rag_agent",
human_input_mode="NEVER",
)

graph_rag_capability = Neo4jGraphCapability(query_engine)
graph_rag_capability.add_to_agent(graph_rag_agent)

user_proxy = UserProxyAgent(name="user_proxy", human_input_mode="ALWAYS", code_execution_config=False, llm_config=llm_config_no_functions)

user_proxy.initiate_chat(graph_rag_agent, message="Please give me any order.")
``` 
Output:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File c:\Users\945764\OneDrive - parkercorp\Desktop\productgpt_diagnose\.venv\Lib\site-packages\llama_index\core\llms\utils.py:42, in resolve_llm(llm, callback_manager)
     [41](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:41)     llm = OpenAI()
---> [42](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:42)     validate_openai_api_key(llm.api_key)  # type: ignore
     [43](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/core/llms/utils.py:43) except ImportError:

File c:\Users\945764\OneDrive - parkercorp\Desktop\productgpt_diagnose\.venv\Lib\site-packages\llama_index\llms\openai\utils.py:507, in validate_openai_api_key(api_key)
    [506](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/llms/openai/utils.py:506) if not openai_api_key:
--> [507](file:///C:/Users/945764/OneDrive%20-%20parkercorp/Desktop/productgpt_diagnose/.venv/Lib/site-packages/llama_index/llms/openai/utils.py:507)     raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)

ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

**Comment by tyler-suard-parker** [comment]
I was able to solve the issue by doing this:

``` 
from llama_index.core import Settings

Settings.llm =llm
Settings.embed_model = embed_model
``` 

Right before declaring the query engine.

**Comment by Eric-Shang** [comment]
Glad that you have solved the problems. I was able to reproduce the error after removing open ai key from my environment. Sorry I didn't realize the key pre-existed (I guess @marklysze may have same setting).

I also found the root cause of the problem. I'll fix it right now and you should be able to use Azure without using Settings.
