### ISSUE TITLE
[Issue]: Can't successfully install CaptainAgent

### ISSUE THREAD

**Issue by marklysze** [ag2ai/ag2#82]
### Describe the issue

Installation according to the documentation is to run:
`pip install ag2[autobuild]`
it should be
`pip install ag2[captainagent]`

However, members of the community (patelnik7, vonullid) on Discord have noted:
- It isn't installing the necessary `pandas` package
- Isn't including the CaptainAgent tools library
- Is failing to install pysqlite3

If you are having issues getting CaptainAgent up and running, please let us know here.

**Comment by marklysze** [comment]
Thanks @learnbydoingwithsteven! Let me have a look into that...

**Comment by bean-du** [comment]
@learnbydoingwithsteven I had the same problem.  Install the sqlite3 and set environments will resolve the problem.
 Mac 
`brew install sqlite3`

and add this into your `.zshrc`. 

```
export LDFLAGS="-L/opt/homebrew/opt/sqlite/lib"
export CPPFLAGS="-I/opt/homebrew/opt/sqlite/include"
```

**Comment by marklysze** [comment]
Thanks for your note and advice on the issue, @bean-du.

I have checked if installing pysqlite3-binary works, and it looks to do so. This avoids the compilation issue with trying to pip install pysqlite3.

I have updated the setup in PR #76, hopefully that helps those in the future.

@learnbydoingwithsteven, if you are still having issues, hopefully #76 will get merged soon. In the meantime, there are instructions in the comments in there on how you could install it.

#76 addresses all the issues noted at the top - so we'll keep the issue open for a short while in case other issues arise, and then we can close it.
