### ISSUE TITLE
[Bug]: Code doesn't work on AWS Lambda function when deployed with attached Role to access bedrock service.

### ISSUE THREAD

**Issue by irshadc** [ag2ai/ag2#84]
### Describe the bug

Current approach hard-coded with accessing bedrock-runtime client to use session with access_credentials. We need to handle a case where it can pick client with attached IAM role to managed service. (boto3.client)

### Steps to reproduce

Simply deploy sample code using lambda function. 
Attach a role to Lambda function which has access to Bedrock Invoke.
No access credentials to be generated and attached in environment, as this is unsecure approach in comparision.

### Model Used

bedrock service, haiku model

### Expected Behavior

Code should connect with bedrock deployed models without need to pass access credential.

**Comment by irshadc** [comment]
Added this pull requests.:#85[Updated bedrock.py to handle case...]

**Comment by marklysze** [comment]
Thanks @irshadc! I'll look through #85 and help get it through.
